#Configure the discovery server
spring:
  application:
    name: eureka-server

eureka:
    numberRegistrySyncRetries: 0
    instance:
        hostname: localhost
    client: #Not a client, don't register with yourself
        region: default
        preferSameZone: false
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    server:
        enableSelfPreservation: false

server:
    port: 1111